package com.itheima.domain.cargo;

import java.io.Serializable;

public class ProductMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_product_message.product_no
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_product_message.product_desc
     *
     * @mbg.generated
     */
    private String productDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_product_message.product_no
     *
     * @return the value of co_product_message.product_no
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_product_message.product_no
     *
     * @param productNo the value for co_product_message.product_no
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_product_message.product_desc
     *
     * @return the value of co_product_message.product_desc
     *
     * @mbg.generated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_product_message.product_desc
     *
     * @param productDesc the value for co_product_message.product_desc
     *
     * @mbg.generated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    @Override
    public String toString() {
        return "ProductMessage{" +
                "productNo='" + productNo + '\'' +
                ", productDesc='" + productDesc + '\'' +
                '}';
    }
}