package com.itheima.domain.cargo;

import java.io.Serializable;

public class ProductMsg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_product_msg.product_no
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_product_msg.loading_rate
     *
     * @mbg.generated
     */
    private String loadingRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_product_msg.product_no
     *
     * @return the value of co_product_msg.product_no
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_product_msg.product_no
     *
     * @param productNo the value for co_product_msg.product_no
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_product_msg.loading_rate
     *
     * @return the value of co_product_msg.loading_rate
     *
     * @mbg.generated
     */
    public String getLoadingRate() {
        return loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_product_msg.loading_rate
     *
     * @param loadingRate the value for co_product_msg.loading_rate
     *
     * @mbg.generated
     */
    public void setLoadingRate(String loadingRate) {
        this.loadingRate = loadingRate == null ? null : loadingRate.trim();
    }

    @Override
    public String toString() {
        return "ProductMsg{" +
                "productNo='" + productNo + '\'' +
                ", loadingRate='" + loadingRate + '\'' +
                '}';
    }
}