package com.itheima.dao.cargo;

import com.itheima.domain.cargo.ProductMsg;
import com.itheima.domain.cargo.ProductMsgExample;

import java.util.List;

public interface ProductMsgDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_product_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_product_msg
     *
     * @mbg.generated
     */
    int insert(ProductMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_product_msg
     *
     * @mbg.generated
     */
    int insertSelective(ProductMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_product_msg
     *
     * @mbg.generated
     */
    List<ProductMsg> selectByExample(ProductMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_product_msg
     *
     * @mbg.generated
     */
    ProductMsg selectByPrimaryKey(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_product_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_product_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductMsg record);
}